site1/blog1/urls.py
from django.urls import path
from . import views
app_name = "blog"
urlpatterns = [
    path('',views.Bloglist.as_view(),name='index'),
    path('blog/<int:pk>', views.Blogviews.as_view(), name="blogt"),
    path('add/', views.add_data, name="insdata"),
    path("add/post_new", views.post_new, name="postnew"),
]

site1/site1/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog1.urls')),
]

site1/blog1/models.py
from django.db import models

# Create your models here.

class Blogpost(models.Model):
    blog_title = models.CharField(max_length=  200)
    blog_description = models.TextField(null=True)

    def __str__(self):
        return self.blog_title

site1/blog1/views.py
from django.shortcuts import render , redirect
from .models import Blogpost
from django.views.generic import ListView, DetailView
# Create your views here.


class Bloglist(ListView):
    context_object_name = 'blogpostfound'
    template_name = 'blogs1/blogpost.html'

    def get_queryset(self):
        return Blogpost.objects.all()


class Blogviews(DetailView):
    model = Blogpost
    template_name = 'blog1/blogdetails.html'

def add_data(request):
    return render(request , 'blog1/blogpostadd.html')

def post_new(request):
    if request.method == "POST":
        print("hi")
        cemetery = Blogpost()
        cemetery.blog_title = request.POST.get('uname')
        cemetery.blog_description = request.POST.get('esal')
        cemetery.save()

    return redirect('/')

site1/blog1/templates/blog1/blogdetails.html
{% extends 'blog1/layout.html' %}

{% block body %}
<h3>The Blog details are:</h3>

<br>
<br>
  <fieldset class="module aligned ">
    <div class="">
      <label for="id_blog_title"><h5>Blog title:</h5></label>
      <input type="text" name="blog_title" value="{{blogpost.blog_title}}" class="vTextField" maxlength="200"  readonly id="id_blog_title" />

    </div>
    <div class="form-row field-blog_description">
      <div class="">
        <label  for="id_blog_description"><h6>Blog description:</h6></label>
        <textarea name="blog_description"  rows="6" class="vLargeTextField" readonly id="id_blog_description">
          {{blogpost.blog_description}}</textarea>
      </div>
    </div>
  </fieldset>


  <br>
  <br>
  <a class="waves-effect waves-light btn-small" onclick="goBack()">back</a>
{% endblock %}

site1/blog1/templates/blog1/blogpost_list.html
{% extends "blog1/layout.html" %}


{%block body %}
  {% if blogpostfound %}
    <h2>The Blog Posts are:</h2>
    <ul>
    {% for ab in blogpostfound %}

        <li><a href="blog\{{ab.pk}}">{{ ab.blog_title}}</a></li>




    {% endfor %}
    </ul>
  {% else %}
    <i>No Blog Post Found</i>
  {% endif %}
<div class="but1">
  <a class="btn-floating btn-large waves-effect waves-light teal"><i class="material-icons" onclick="window.location.href='add/'">add</i></a>


</form>
</div>

{%endblock%}

site1/blog1/templates/blog1/blogpostadd.html
{% extends 'blog1/layout.html' %}

{% block body %}
<h5>Add Your Blog Post Details</h5>
<br>
<br>
  <fieldset class="module aligned ">
    <form class="" action="post_new" method="post">
      {% csrf_token %}

    <div class="">
      <label for="id_blog_title"><h5>Blog title:</h5></label>
      <input type="text" name="uname" value="" class="vTextField" maxlength="200"  required id="id_blog_title" />

    </div>
    <div class="form-row field-blog_description">
      <div class="">
        <label  for="id_blog_description"><h6>Blog description:</h6></label>
        <textarea name="esal" rows="6" class="vLargeTextField" required id="esal">
          </textarea>
      </div>
    </div>

    <br> <br>
    <input type="submit" class="waves-effect waves-light btn-small" value="Add Post">
    <br>
    </form>
  </fieldset>


  <br>
  <br>

  <a class="waves-effect waves-light btn-small" onclick="goBack()">back</a>
{% endblock %}

site1/blog1/templates/blog1/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Blogs App</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <script>
    function goBack() {
      window.history.back();
      }

      function addpost() {
        alert('hi');
      }


      
    </script>
    <style media="screen">
          body {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
      }

      main {
        flex: 1 0 auto;
      }

      .page-footer {
  background-color: #50acaf ;//#2ca395;
}
  .but1 {
  position: absolute;
  right:    50px;
  bottom:   102px;
  }
  textarea { height: auto; }

    </style>
  </head>


<main>

  <body>

    <div class="container">


  {%block body%}

  {% endblock %}
</div>


  </body>


</main>
  <footer class="page-footer">
    <div class="container">

      Simple Blog APP

          </div>
  </footer>

</html>